name: 'Seal Of Approval'
description: 'Github action that gives seal of approval to your PR.'
author: 'Andriy Chemerynskiy'
branding:
  icon: 'code'  
  color: 'blue'
inputs:
  GITHUB_TOKEN:        #Github token      
    description: 'Github token for the repository.'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'